List<Map<String, dynamic>> eventList = [
  {
    'eventId': '1',
    'eventName': 'Somaroho Celebration',
    'eventDate': '2023-07-15T12:00:00Z',
    'eventLocation': 'Antananarivo, Madagascar',
    'eventBannerUrl': 'https://example.com/somaroho-celebration.jpg',
  },
  {
    'eventId': '2',
    'eventName': 'Malagasy Independence Day Parade',
    'eventDate': '2023-06-26T10:00:00Z',
    'eventLocation': 'Various cities in Madagascar',
    'eventBannerUrl': 'https://example.com/independence-day-parade.jpg',
  },
  {
    'eventId': '3',
    'eventName': 'Tsakitsaky Music Festival',
    'eventDate': '2023-08-20T19:00:00Z',
    'eventLocation': 'Nosy Be, Madagascar',
    'eventBannerUrl': 'https://example.com/tsakitsaky-music-festival.jpg',
  },
  {
    'eventId': '4',
    'eventName': 'Antananarivo Arts and Crafts Fair',
    'eventDate': '2023-09-10T11:00:00Z',
    'eventLocation': 'Antananarivo, Madagascar',
    'eventBannerUrl': 'https://example.com/arts-crafts-fair.jpg',
  },
  {
    'eventId': '5',
    'eventName': 'Madagascar Film Festival',
    'eventDate': '2023-11-05T17:30:00Z',
    'eventLocation': 'Antsiranana, Madagascar',
    'eventBannerUrl': 'https://example.com/madagascar-film-festival.jpg',
  },
  {
    'eventId': '6',
    'eventName': 'Zebu Racing Championship',
    'eventDate': '2023-10-15T14:00:00Z',
    'eventLocation': 'Fianarantsoa, Madagascar',
    'eventBannerUrl': 'https://example.com/zebu-racing-championship.jpg',
  },
  {
    'eventId': '7',
    'eventName': 'Makay Mountain Trekking Expedition',
    'eventDate': '2023-12-01T08:00:00Z',
    'eventLocation': 'Makay Massif, Madagascar',
    'eventBannerUrl': 'https://example.com/makay-trekking-expedition.jpg',
  },
  {
    'eventId': '8',
    'eventName': 'Vanilla Festival',
    'eventDate': '2023-11-20T15:30:00Z',
    'eventLocation': 'Sambava, Madagascar',
    'eventBannerUrl': 'https://example.com/vanilla-festival.jpg',
  },
  {
    'eventId': '9',
    'eventName': 'Morondava Baobab Festival',
    'eventDate': '2023-10-05T16:00:00Z',
    'eventLocation': 'Morondava, Madagascar',
    'eventBannerUrl': 'https://example.com/baobab-festival.jpg',
  },
  {
    'eventId': '10',
    'eventName': 'Traditional Malagasy Dance Competition',
    'eventDate': '2023-09-25T13:30:00Z',
    'eventLocation': 'Toamasina, Madagascar',
    'eventBannerUrl': 'https://example.com/malagasy-dance-competition.jpg',
  },
];